-- 테이블 제거
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE WORKER CASCADE CONSTRAINTS;
DROP TABLE NCOMMENT CASCADE CONSTRAINTS;
DROP SEQUENCE NOTICE_SEQ;
DROP SEQUENCE NCOMMENT_SQ;
-- 시퀀스 생성
CREATE SEQUENCE NOTICE_SEQ NOCACHE NOCYCLE;
CREATE SEQUENCE NCOMMENT_SQ NOCACHE NOCYCLE;

-- 테이블 생성
CREATE TABLE WORKER(
    WID VARCHAR2(20) PRIMARY KEY,
    WPW VARCHAR2(20) NOT NULL,
    WNAME VARCHAR2(20) NOT NULL,
    WPHONE VARCHAR2(20)
    );


CREATE TABLE NOTICE(
    NID NUMBER(5) PRIMARY KEY,
    NTITLE VARCHAR2(100),
    NCONTENT VARCHAR2(1000),
    NTEXT VARCHAR2(3000),
    NRDATE DATE DEFAULT SYSDATE,
    WID VARCHAR2(20) REFERENCES WORKER(WID)
    );

CREATE TABLE NCOMMENT(
    CNUM NUMBER(5) PRIMARY KEY,
    NID NUMBER(6) REFERENCES NOTICE(NID) NOT NULL,
    CNAME VARCHAR2(100) NOT NULL,
    CMEMO VARCHAR2(4000) NOT NULL,
    CDATE DATE DEFAULT SYSDATE NOT NULL,
    CGROUP NUMBER(5) NOT NULL,
    CSTEP NUMBER(2) NOT NULL,
    CINDENT NUMBER(2) NOT NULL,
    CIP VARCHAR2(20) NOT NULL
);

--    REFERENCES MEMBER (MID);

-- 검색
SELECT * FROM NOTICE;

-- 관리자 더미데이터
INSERT INTO WORKER VALUES('admin','1234', '관리자', '010-7777-7777');
    
SELECT * FROM WORKER;

-- 공지사항 리스트
INSERT INTO NOTICE (NID, NTITLE, NCONTENT, NTEXT, NRDATE, WID)
    VALUES(NOTICE_SEQ.NEXTVAL, '산타 빌리지 투어 and 산타의 미라클 프레젠트', 'santa.jpg', '내용', SYSDATE , 'admin');
INSERT INTO NOTICE (NID, NTITLE, NCONTENT, NTEXT, NRDATE, WID)
    VALUES(NOTICE_SEQ.NEXTVAL, '이용예약제 안내(키즈토리아, 언더씨킹덤) 안내', '이용예약제.jpg','내용', SYSDATE , 'admin');
INSERT INTO NOTICE (NID, NTITLE, NCONTENT, NTEXT, NRDATE, WID)
    VALUES(NOTICE_SEQ.NEXTVAL, '풍선비행 탑승예약제 안내', '풍선비행.jpg', '내용', SYSDATE , 'admin');
INSERT INTO NOTICE (NID, NTITLE, NCONTENT, NTEXT, NRDATE, WID)
    VALUES(NOTICE_SEQ.NEXTVAL, '신규 어트랙션 <배틀그라운드 월드 에이전트> OPEN', 'bg.jpg', '내용', SYSDATE , 'admin');
INSERT INTO NOTICE (NID, NTITLE, NCONTENT, NTEXT, NRDATE, WID)
    VALUES(NOTICE_SEQ.NEXTVAL, '주차시스템 개선 안내', 'parking.jpg', '내용', SYSDATE , 'admin');
INSERT INTO NOTICE (NID, NTITLE, NCONTENT, NTEXT, NRDATE, WID)
    VALUES(NOTICE_SEQ.NEXTVAL, '탑승예약제(스페인해적선, 후렌치레볼루션) 안내', 'yo.jpg', '내용', SYSDATE , 'admin');
INSERT INTO NOTICE (NID, NTITLE, NCONTENT, NTEXT, NRDATE, WID)
    VALUES(NOTICE_SEQ.NEXTVAL, '장애인 탑승예약제 시행 안내', 'hh.jpg', '내용', SYSDATE , 'admin');

-- worker dao

-- 비번찾기 id=getWpw
SELECT WPW FROM WORKER WHERE WID='admin';

-- 이름찾기 id=getWname
SELECT WNAME FROM WORKER WHERE WID='admin';

-- 워커 카운트 id=getAllCount
SELECT COUNT(*) FROM WORKER;

-- NOTICE DAO

-- 공지사항 리스트 id=NoticeList
SELECT * FROM NOTICE WHERE NTITLE LIKE '%' || '결' || '%' ORDER BY NID DESC;
SELECT * 
    FROM (SELECT ROWNUM RN, A.* 
        FROM(SELECT * FROM NOTICE
            WHERE UPPER(NTITLE) LIKE '%' || UPPER('결') || '%' ORDER BY NID DESC) A)
        WHERE RN BETWEEN 1 AND 4;
-- 전체 공지사항 리스트
SELECT * FROM NOTICE ORDER BY NTITLE;
SELECT ROWNUM RN, A.*
    FROM (SELECT * FROM NOTICE ORDER BY NTITLE) A;
SELECT *
    FROM (SELECT ROWNUM RN, A.*
        FROM (SELECT * FROM NOTICE ORDER BY NTITLE) A)
    WHERE RN BETWEEN 1 AND 5;
-- 전체 공시사항 리스트 id=totCntNotice
SELECT COUNT(*) FROM NOTICE;
-- 검색했을 때 공지사항 몇개인지
SELECT COUNT(*) FROM NOTICE WHERE UPPER(NTITLE) LIKE'%' || UPPER('결') || '%';
-- 공지번호로 가져오기 id=getDetailBook(dto가져오기 번호로)
SELECT * FROM NOTICE WHERE NID=2;

-- 공지insert id=insertNotice
INSERT INTO NOTICE (NID, NTITLE, NCONTENT, NTEXT, NRDATE, WID)
    VALUES(NOTICE_SEQ.NEXTVAL, '결제가 안돼요', 'noImg.png','내용', SYSDATE , 'admin');
-- 공지수정 id=updateNotice
UPDATE NOTICE SET
        NTITLE = '공지수정',
        NCONTENT = 'noImg.png',
        NTEXT = '내용',
        NRDATE = SYSDATE,
        WID = 'admin'
    WHERE NID=2;
SELECT * FROM NOTICE;
-- 공지삭제 id=deleteNotice
DELETE FROM NOTICE WHERE NID=1;
COMMIT;

-- worker Attraction
-- 어트랙션 검색 id=attractionListP
SELECT * 
    FROM (SELECT ROWNUM RN, A.* 
        FROM(SELECT * FROM ATTRACTION
            WHERE UPPER(ANAME) LIKE '%' || UPPER('범') || '%' ORDER BY AID DESC) A)
        WHERE RN BETWEEN 1 AND 4;
-- 어트랙션 insert id=insertAttraction
INSERT INTO ATTRACTION (AID, ANAME, ACONTENT, HEIGHT, AGE, BEST, STOPDAY, TAG1, TAG2, AIMAGE, HEADCOUNT)
VALUES
(ATTRACTION_SEQ.NEXTVAL, '범퍼카' ,'화려한 조명과 신나는 음악 속에서 스릴만점의 자동차 경주가 펼쳐진다. 
앞에서 쾅~ 뒤에서 쾅~ 어디서 달려들지 모르는 좌충우돌 범퍼카! 부딪칠수록 즐거움이 더욱 커집니다.',
'125cm 이상 탑승가능', '65세 이하 탑승 가능', 'Y', 'N', '익사이팅', '어린이', 'car.jpg', 1);
-- 어트랙션 update id=updateAttraction
UPDATE ATTRACTION SET
        ANAME = '왕밤빵카',
        ACONTENT = '화려한 조명이 날 비추네',
        HEIGHT = '180cm이상탑승가능',
        AGE = '75세 이하 탑승가능',
        BEST = 'N',
        STOPDAY = 'Y',
        TAG1 = '익사이팅',
        TAG2 = '어른이',
        AIMAGE = 'car.jpg',
        HEADCOUNT = 2
    WHERE AID = 2;
-- 어트랙션 갯수 id=totCntAttraction
SELECT COUNT(*) FROM ATTRACTION WHERE UPPER(ANAME) LIKE'%' || UPPER('범') || '%';
-- 어트랙션 delete id=deleteAttraction
DELETE FROM ATTRACTION WHERE AID=1;
SELECT * FROM MEMBER;


-- workerBanner Dao
  
-- 배너 리스트 id=bannerList
SELECT * FROM BANNER; ORDER BY BORDER;
-- 새배너 만들기 id=insertBanner
INSERT INTO BANNER (BNO, BTITLE, BORDER, USAGE, BIMG)
    VALUES (BANNER_SEQ.NEXTVAL, '배너1', '1', 'Y', 'banner1.jpg');
-- 배너 순서변경 id=updateSeq
UPDATE BANNER SET
        BORDER = '1',
        USAGE = 'Y',
        BIMG = 'mainimgs1.jpg'
    WHERE BNO = '1';
-- 배너 제거 id=deleteBanner
DELETE FROM BANNER WHERE BNO = '1';
-- 배너 갯수 id=cntBanner
SELECT COUNT(*) FROM BANNER;

DELETE FROM NCOMMENT WHERE CNAME='말똥이';
SELECT * FROM NCOMMENT;
-- NOTICE COMTENT DAO
-- 댓글 쓰기 (id = commentWrite)
INSERT INTO NCOMMENT (CNUM, NID, CNAME, CMEMO, CGROUP, CSTEP, CINDENT, CIP)
    VALUES (NCOMMENT_SQ.NEXTVAL, 3, '개똥이','좋아요',NCOMMENT_SQ.CURRVAL, 0,0, '127.0.0.');
INSERT INTO NCOMMENT (CNUM, NID, CNAME, CMEMO, CGROUP, CSTEP, CINDENT, CIP)
    VALUES (NCOMMENT_SQ.NEXTVAL, 3, '소똥이','두번째로 좋아요',NCOMMENT_SQ.CURRVAL, 0,0, '127.0.0.');
INSERT INTO NCOMMENT (CNUM, NID, CNAME, CMEMO, CGROUP, CSTEP, CINDENT, CIP)
    VALUES (NCOMMENT_SQ.NEXTVAL, 3, '말똥이','세번째로 좋아요',NCOMMENT_SQ.CURRVAL, 0,0, '127.0.0.');
-- 상세보기에서 댓글리스트(id = commentList)
SELECT * FROM NCOMMENT WHERE NID=3 ORDER BY CGROUP DESC, CSTEP;
SELECT * 
    FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM NCOMMENT WHERE NID=3 ORDER BY CGROUP DESC, CSTEP) A)
    WHERE RN BETWEEN 1 AND 4;
-- 댓글 갯수(id = commentTotCnt)
SELECT COUNT(*) FROM NCOMMENT WHERE NID=3;
-- 답변 댓글 쓰기 전 (id = commentReplyPreStep)
UPDATE NCOMMENT SET CSTEP=CSTEP+1 WHERE CGROUP=2 AND CSTEP>0;
-- 답변 댓글 쓰기 (id = commentReply)
INSERT INTO NCOMMENT (CNUM, NID, CNAME, CMEMO, CGROUP, CSTEP, CINDENT, CIP)
    VALUES (NCOMMENT_SQ.NEXTVAL, 3, '답쟁이','뭐가 좋아요',2, 1,1, '127.0.0.');
UPDATE NCOMMENT SET CSTEP=CSTEP+1 WHERE CGROUP=2 AND CSTEP>0;
INSERT INTO NCOMMENT (CNUM, NID, CNAME, CMEMO, CGROUP, CSTEP, CINDENT, CIP)
    VALUES (NCOMMENT_SQ.NEXTVAL, 3, '답쟁이','대답하세요',2, 1,1, '127.0.0.');
-- 댓글 수정( id = commentModify) (미구현)
UPDATE NCOMMENT SET
    CNAME = '홍길동',
    CMEMO = '그렇죠',
    CDATE = SYSDATE,
    CIP = '127.0.0.1'
    WHERE CNUM=1;
-- 댓글 삭제 (id = commentDelete)
DELETE FROM NCOMMENT WHERE CNUM=1;
SELECT * FROM NCOMMENT WHERE NID=3 ORDER BY CGROUP DESC, CSTEP;
-- 댓글 전부삭제 관리자가 공지삭제시 필요 (id=deleteAllComments)
DELETE FROM NCOMMENT WHERE NID=1;
ROLLBACK;
SELECT NCOMMENT_SQ.CURRVAL FROM NCOMMENT;
-- 댓글번호로 댓글 dto 가져오기(id = commentDetail)
SELECT * FROM NCOMMENT WHERE CNUM=1;
SELECT * FROM NCOMMENT;
commit;

    

    
   


    