-- 테이블 제거
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE WORKER CASCADE CONSTRAINTS;
DROP SEQUENCE NOTICE_SEQ;

-- 시퀀스 생성
CREATE SEQUENCE NOTICE_SEQ;


-- 테이블 생성
CREATE TABLE WORKER(
    WID VARCHAR2(20) PRIMARY KEY,
    WPW VARCHAR2(20) NOT NULL,
    WNAME VARCHAR2(20) NOT NULL,
    WPHONE VARCHAR2(20)
    );


CREATE TABLE NOTICE(
    NID NUMBER(5) PRIMARY KEY,
    NTITLE VARCHAR2(100),
    NCONTENT VARCHAR2(1000),
    NRDATE DATE DEFAULT SYSDATE,
    WID VARCHAR2(20) REFERENCES WORKER(WID)
    );
    

--    REFERENCES MEMBER (MID);

-- 검색
SELECT * FROM NOTICE;

-- 관리자 더미데이터
INSERT INTO WORKER VALUES('admin','1234', '관리자', '010-7777-7777');
    
SELECT * FROM WORKER;

-- 공지사항 리스트
INSERT INTO NOTICE (NID, NTITLE, NCONTENT, NRDATE, WID)
    VALUES(NOTICE_SEQ.NEXTVAL, '결제가 안돼요', 'ㅠㅠ', SYSDATE , 'admin');
INSERT INTO NOTICE (NID, NTITLE, NCONTENT, NRDATE, WID)
    VALUES(NOTICE_SEQ.NEXTVAL, '티켓교환은 어떻게 하나요?', 'ㅠㅠ', SYSDATE , 'admin');
INSERT INTO NOTICE (NID, NTITLE, NCONTENT, NRDATE, WID)
    VALUES(NOTICE_SEQ.NEXTVAL, '집에 언제가나요?', 'ㅠㅠ', SYSDATE , 'admin');
INSERT INTO NOTICE (NID, NTITLE, NCONTENT, NRDATE, WID)
    VALUES(NOTICE_SEQ.NEXTVAL, '배고파요', 'ㅠㅠ', SYSDATE , 'admin');
INSERT INTO NOTICE (NID, NTITLE, NCONTENT, NRDATE, WID)
    VALUES(NOTICE_SEQ.NEXTVAL, '우와 금요일이에요', 'ㅎㅎ', SYSDATE , 'admin');
INSERT INTO NOTICE (NID, NTITLE, NCONTENT, NRDATE, WID)
    VALUES(NOTICE_SEQ.NEXTVAL, '내일은 주말이에요', 'ㅎㅎ', SYSDATE , 'admin');
INSERT INTO NOTICE (NID, NTITLE, NCONTENT, NRDATE, WID)
    VALUES(NOTICE_SEQ.NEXTVAL, '추워요', 'ㅠㅠ', SYSDATE , 'admin');
    
    
-- worker dao

-- 비번찾기 id=getWpw
SELECT WPW FROM WORKER WHERE WID='admin';

-- 이름찾기 id=getWname
SELECT WNAME FROM WORKER WHERE WID='admin';

-- 워커 카운트 id=getAllCount
SELECT COUNT(*) FROM WORKER;

-- NOTICE DAO

-- 공지사항 리스트
SELECT * FROM NOTICE WHERE NTITLE LIKE '%' || '결' || '%' ORDER BY NID DESC;
SELECT * 
    FROM (SELECT ROWNUM RN, A.* 
        FROM(SELECT * FROM NOTICE
            WHERE NTITLE LIKE '%' || '결' || '%' ORDER BY NID DESC) A)
        WHERE RN BETWEEN 1 AND 4;
        
-- 공지번호로 가져오기 id=listNotice
SELECT * FROM NOTICE WHERE NID=2;

-- 
    

    