--qna
--DROP TABLE
DROP TABLE QNA CASCADE CONSTRAINTS;
DROP SEQUENCE QNA_SEQ; 
--CREATE TABLE
CREATE SEQUENCE QNA_SEQ MAXVALUE 99999 NOCACHE NOCYCLE;
CREATE TABLE QNA(
    QNO NUMBER(5) NOT NULL PRIMARY KEY,
    QTITLE VARCHAR2 (100),
    QCONTENT VARCHAR2 (1000),
    QPW VARCHAR2(500),
    ISREPLY VARCHAR2(1) DEFAULT 'N',
    QRDATE DATE DEFAULT SYSDATE,
    QGROUP NUMBER(5) NOT NULL,
    QSTEP NUMBER(3),
    QINDENT NUMBER(3),
      MID VARCHAR2 (20)
    REFERENCES MEMBER(MID) NOT NULL
);
INSERT INTO QNA (QNO,QTITLE,QCONTENT,QGROUP,QSTEP,QINDENT,MID) VALUES
(QNA_SEQ.NEXTVAL,'단체관람 할인','동호회 단체관람 예정인데 할인 방법이있나요', QNA_SEQ.CURRVAL,0,0,'one');
SELECT * FROM QNA;

COMMIT;
--ID  = getAllCount
select count(*) from QNA;
select count(*) from  QNA where QTITLE like '%'||'단'||'%';
SELECT * FROM Qna;
--ID = listQna
SELECT * FROM
    (SELECT ROWNUM RN, A.* FROM(SELECT * FROM QNA WHERE QTITLE LIKE '%'||'단'||'%' ORDER BY QNO DESC)A)
    WHERE RN BETWEEN 1 AND 5;
SELECT * FROM
    (SELECT ROWNUM RN, A.* FROM(SELECT * FROM QNA ORDER BY QNO DESC)A)
    WHERE RN BETWEEN 1 AND 5;
--ID = getQna
SELECT * FROM QNA WHERE QNO = 1;
--ID = insertQna
INSERT INTO QNA (QNO,QTITLE,QCONTENT,QPW,QGROUP,QSTEP,QINDENT,MID) VALUES
(QNA_SEQ.NEXTVAL,'단체관람 할인','동호회 단체관람 예정인데 할인 방법이있나요','123', QNA_SEQ.CURRVAL,0,0,'one');
commit;
--id =QnaPreReplyStep
UPDATE QNA SET QSTEP = QSTEP+1 WHERE QGROUP = 5 AND QSTEP > 0;
--id =QnaPreReply
INSERT INTO QNA (QNO,QTITLE,QCONTENT,QPW,QGROUP,QSTEP,QINDENT,MID) VALUES
(QNA_SEQ.NEXTVAL,'단체관람 할인[답]','동호회 단체관람 예정인데 할인 방법이있나요','123',5,1,1,'one');
commit;








